# Telegram messaging private keys
TELEPOT_BOT = 'XXXXXXXXXX:YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'
CHAT_ID = "-ZZZZZZZZZ"
TELEPOT_BOT_TEST = 'XXXXXXXXXX:YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'
CHAT_ID_TEST = "-ZZZZZZZZZ"

LOC_STRING = ""
# Python Anywhere config
PA_USERNAME = 'XXXXX'
PA_API_TOKEN = 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'