# Telegram messaging private keys
TELEPOT_BOT = 'XXXXXXXXXX:YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'
CHAT_ID = "-ZZZZZZZZZ"
TELEPOT_BOT_TEST = 'XXXXXXXXXX:YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'
CHAT_ID_TEST = "-ZZZZZZZZZ"

# Python Anywhere config
use_local_config_or_pythonanywhere = False
PA_USERNAME = 'XXXXX'
PA_API_TOKEN = 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'