---
SETTINGS:
  ta_list_global:
    - "OUT_OF_BBANDS"
    - "CASH_OUT_RSI"
    - "MA21_ENVELOPE" 
TICKERS:
  BTC-USD:
    label: "BTCUSDT"
    ta_list:
      - "EMA_TREND"
      - "RSI_SELL_OF"
      - "RSI_WEEK_SELL_OF"
    trends:
      Long Exp Resistance:
        kind: "Exp"
        coordinate1: ["2016-02-01", 35]
        coordinate2: ["2020-09-21", 10620]
        alert_condition: "Alert_Below"
  ETH-USD:
    label: "ETHUSDT"
    something: [100, 100,0.05,0.05, 10,10]
    ta_list:
      - "EMA_TREND"
    trends:
  SOL-USD:
    label: "SOLUSDT"
    something: [100, 100,0.05,0.05, 10,10]
    ta_list:
      - "EMA_TREND"
      - "RSI_SELL_OF"
    trends:

